# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 542909520046675dd5ac1de0323697d8f8a245fe022c3138ba2f0283cc4fcdebe2f4a30de991a222cd9b6dbdec1d290ec3d5708d46b8a11d24a816fada76640b

test:
  secret_key_base: e15f7a191d0fa602ed9bb929fde0c4d56ea8bac3b72f542a87033a512062b2638a80592fcaee406e12ec94e95595a171fdbdc4b95c3a57945b2701d77a5e30b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
