# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b8953a67c2e18db20063d440a26ae50ecac1b5e4f74aeca52265deb698ad95f9926ebbd701cd4179892f4c7781fd90502f64689fe00307c1db50d908cd47a3ee

test:
  secret_key_base: 5dd6909106ddcfe6da352299925c5a139f08911e6bbbd63f57cdbccb281512a9e03ca27d5f213fd140721d572214387fc2cb5b9be2fd11b23357b4b002e21db5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
